#!/bin/bash
# Safe Project Cleanup Script
# This script removes duplicate and unnecessary files with verification at each step

set -e  # Exit on error

echo "🧹 MUNEEM Project Cleanup Script"
echo "================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to verify application health
verify_health() {
    echo -n "Checking application health... "
    if curl -s http://localhost:8000/api/v1/health | grep -q "ok"; then
        echo -e "${GREEN}✓ Backend healthy${NC}"
    else
        echo -e "${RED}✗ Backend not responding${NC}"
        return 1
    fi
    
    if curl -s http://localhost:5173 > /dev/null 2>&1; then
        echo -e "${GREEN}✓ Frontend healthy${NC}"
    else
        echo -e "${RED}✗ Frontend not responding${NC}"
        return 1
    fi
}

# Initial health check
echo "Step 0: Initial Health Check"
verify_health || { echo "Application not running. Please start it first."; exit 1; }
echo ""

# Step 1: Remove .DS_Store files (safe, regenerated by macOS)
echo "Step 1: Removing .DS_Store files"
echo "Files to remove:"
find . -name ".DS_Store" -type f
read -p "Proceed with removal? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    find . -name ".DS_Store" -type f -delete
    echo -e "${GREEN}✓ .DS_Store files removed${NC}"
fi
echo ""

# Step 2: Remove test_ocr.py from root (temporary test file)
echo "Step 2: Removing temporary test file"
if [ -f "test_ocr.py" ]; then
    echo "File: test_ocr.py ($(wc -l < test_ocr.py) lines)"
    read -p "Remove test_ocr.py? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm test_ocr.py
        echo -e "${GREEN}✓ test_ocr.py removed${NC}"
    fi
else
    echo "test_ocr.py not found, skipping"
fi
echo ""

# Step 3: Remove 'haven't' directory (failed venv installation)
echo "Step 3: Removing failed venv installation"
HAVENT_DIR="backend/services/paddle_ocr/haven't"
if [ -d "$HAVENT_DIR" ]; then
    SIZE=$(du -sh "$HAVENT_DIR" | cut -f1)
    echo "Directory: $HAVENT_DIR (Size: $SIZE)"
    echo "This appears to be a failed/incomplete virtual environment installation"
    read -p "Remove this directory? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$HAVENT_DIR"
        echo -e "${GREEN}✓ 'haven't' directory removed${NC}"
        
        # Verify venv still works
        echo "Verifying active venv..."
        cd backend/services/paddle_ocr
        source venv/bin/activate
        python -c "import paddleocr; print('✓ Active venv still works')" || {
            echo -e "${RED}✗ Active venv broken! Restore from backup!${NC}"
            exit 1
        }
        cd ../../..
    fi
else
    echo "'haven't' directory not found, skipping"
fi
echo ""

# Step 4: Remove __pycache__ directories (regenerated automatically)
echo "Step 4: Removing Python cache directories"
echo "Finding __pycache__ directories..."
find . -type d -name "__pycache__" | grep -v node_modules | grep -v venv | head -10
read -p "Remove all __pycache__ directories? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    echo -e "${GREEN}✓ __pycache__ directories removed${NC}"
fi
echo ""

# Final health check
echo "Final Health Check"
verify_health || {
    echo -e "${RED}✗ Application health check failed after cleanup!${NC}"
    echo "Please investigate and restore from backup if needed"
    exit 1
}

echo ""
echo -e "${GREEN}✅ Cleanup completed successfully!${NC}"
echo ""
echo "Summary:"
echo "- Removed macOS system files (.DS_Store)"
echo "- Removed temporary test files"
echo "- Removed failed venv installation"
echo "- Removed Python cache directories"
echo "- Application verified healthy"
